apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend
spec:
  type: NodePort
  ports:
  - name: "backend-service"
    port: 7200
    targetPort: 7200
    nodePort: 31001
  selector:
    app: backend
